Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Library.Controllers
{
    public class BooksController : LibraryController
    {
        // GET: Books
        public ActionResult Index()
        {
            Models.LibraryTableAdapters.BooksTableAdapter booksAdapter=new Models.LibraryTableAdapters.BooksTableAdapter();
            Models.Library.BooksDataTable booksTable=new Models.Library.BooksDataTable();

            booksAdapter.Fill(booksTable);
            ViewData["books"] = booksTable.Rows;
            ViewData["title"] = "Kitaplar";
            return View();
        }
    }
}

Controllers/MembersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net.Mail;

namespace Library.Controllers
{
    public class MembersController : LibraryController
    {
        // GET: Members
        public ActionResult Index()
        {
            Models.LibraryTableAdapters.MembersTableAdapter membersAdapter = new Models.LibraryTableAdapters.MembersTableAdapter();
            Models.Library.MembersDataTable membersTable = new Models.Library.MembersDataTable();

            membersAdapter.Fill(membersTable);
            ViewData["members"] = membersTable.Rows;
            ViewData["title"] = "Üyeler";
            return View();
           
        }
        public ActionResult Update(long id, string error = null)
        {
            Models.LibraryTableAdapters.MembersTableAdapter membersAdapter = new Models.LibraryTableAdapters.MembersTableAdapter();
            Models.Library.MembersDataTable membersTable = new Models.Library.MembersDataTable();
            Models.Library.MembersRow memberRow;
            membersAdapter.FillById(membersTable, id);
            memberRow=(Models.Library.MembersRow)membersTable.Rows[0];
            ViewData["title"] = memberRow.MemberName + " " + memberRow.MemberSurname; 
            ViewData["memberRow"] = memberRow;
            if(error != null)
            {
                ViewData["error"] = error;
            }

            return View();
        }
        public void ProcessMember(long originalId ,long memberId,string name ,string surname, long phone ,string eMail , string address, bool banned=false,bool? gender=null)
        {
            Models.LibraryTableAdapters.MembersTableAdapter membersAdapter;
            if (memberId.ToString().Length != 11)
            {
                Response.Redirect("~/members/update/" + originalId.ToString());
                return;
            }
            if(name== null)
            {
                Response.Redirect("~/members/update/" + originalId.ToString());
                return;
            }
            name= name.Trim();
            if (name == "")
            {
                Response.Redirect("~/members/update/" + originalId.ToString());
                return;
            }
            if (name.Length > 50)
            {
                Response.Redirect("~/members/update/" + originalId.ToString());
                return;
            }
            if (surname == null)
            {
                Response.Redirect("~/members/update/" + originalId.ToString());
                return;
            }
            surname = surname.Trim();
            if (name == "")
            {
                Response.Redirect("~/members/update/" + originalId.ToString());
                return;
            }
            if (surname.Length > 50)
            {
                Response.Redirect("~/members/update/" + originalId.ToString());
                return;
            }
            if (phone.ToString().Length != 10)
            {
                Response.Redirect("~/members/update/" + originalId.ToString());
                return;
            }
            if (eMail == null)
            {
                Response.Redirect("~/members/update/" + originalId.ToString());
                return;
            }
            eMail= eMail.Trim();
            if(eMail.Length > 100)
            {
                Response.Redirect("~/members/update/" + originalId.ToString());
                return;
            }
            try
            {
                membersAdapter = new Models.LibraryTableAdapters.MembersTableAdapter();
                membersAdapter.UpdateMembers(memberId, banned , phone, gender, name, surname,eMail,address,originalId);
                Response.Redirect("~/members");
            }
            catch
            {
                Response.Redirect("~/members/update/" + originalId.ToString());
            }
        }
        public ActionResult MemberData(long id)
        {
            Models.LibraryTableAdapters.MembersTableAdapter membersAdapter = new Models.LibraryTableAdapters.MembersTableAdapter();
            Models.Library.MembersDataTable membersTable = new Models.Library.MembersDataTable();

            membersAdapter.FillById(membersTable, id);
            if (membersTable.Rows.Count > 0)
            {
                ViewData["memberRow"] = (Models.Library.MembersRow)membersTable.Rows[0];
            }
           

            return PartialView();
        }
        public bool MemberExists(long id)
        {
            Models.LibraryTableAdapters.MembersTableAdapter membersAdapter = new Models.LibraryTableAdapters.MembersTableAdapter();
            int memberCount = membersAdapter.MemberCount(id).Value;

            if(memberCount==0)
            { 
                return false; 
            }

            return true;
        }
        public void ProcessNewMember(long id, string memberName, string memberSurname, long memberPhone, string memberEMail,string memberAddress,bool? gender)
        {
            Models.LibraryTableAdapters.MembersTableAdapter membersAdapter = new Models.LibraryTableAdapters.MembersTableAdapter();
            membersAdapter.AddMember(id,memberName,memberSurname,memberPhone,memberEMail,gender, memberAddress);
        }
    }
}

Controllers/RentalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Library.Controllers
{
    public class RentalsController : LibraryController
    {

        public ActionResult Index(string error=null)
        {
            if (error != null)
            {
                if (error != "")
                {
                    ViewData["error"] = error;
                }
            }
            return View();
        }
        public void ProcessRental(long bookId, long memberId)
        {
            MembersController membersController = new MembersController();
            bool? gender = null;
            Models.LibraryTableAdapters.QueriesTableAdapter queriesAdapter = new Models.LibraryTableAdapters.QueriesTableAdapter();
            Models.LibraryTableAdapters.BooksTableAdapter booksAdapter = new Models.LibraryTableAdapters.BooksTableAdapter();
            Models.LibraryTableAdapters.RentalsTableAdapter rentalsAdapter = new Models.LibraryTableAdapters.RentalsTableAdapter();
            Models.LibraryTableAdapters.MovesTableAdapter movesAdapter = new Models.LibraryTableAdapters.MovesTableAdapter();
            Models.Library.MovesDataTable movesTable = new Models.Library.MovesDataTable();

            string error = "";
            if (membersController.MemberExists(memberId) == false)
            {
                if (Request.Params["gender"] != null)
                {
                    gender = Convert.ToBoolean(Request.Params["gender"]);
                }
                membersController.ProcessNewMember(memberId, Request.Params["memberName"], Request.Params["memberSurname"], Convert.ToInt64(Request.Params["memberPhone"]), Request.Params["memberEMail"], Request.Params["memberAddress"], gender);
            }
            if (rentalsAdapter.CheckRent(memberId, bookId).Value == 0)
            {
                queriesAdapter.AddRental(memberId, bookId, DateTime.Today, DateTime.Today.AddDays(30));

            }
            else
            {
                error = "Bu kitap zaten ödünç verilmiştir.";
            }
            booksAdapter.DecreaseActiveStock(bookId);
            movesAdapter.AddMoves(memberId, bookId, DateTime.Today, true);
            ViewData["moves"] = movesTable.Rows;

            Response.Redirect("~/rentals?error"+error);
        }
        public ActionResult ReturnBook(string bookId)
        {
          return View();
        }
        public ActionResult CurrentRentals(long id)
        {
            Models.LibraryTableAdapters.RentalsTableAdapter rentalsAdapter = new Models.LibraryTableAdapters.RentalsTableAdapter();
            Models.Library.RentalsDataTable rentalsTable = new Models.Library.RentalsDataTable();
            rentalsAdapter.Fill(rentalsTable, id);
            ViewData["rentals"] = rentalsTable.Rows;


            return PartialView();
        }
        public void ProcessReturn(long bookId,long member)
        {
            Models.LibraryTableAdapters.RentalsTableAdapter rentalsAdapter = new Models.LibraryTableAdapters.RentalsTableAdapter();
            Models.LibraryTableAdapters.BooksTableAdapter booksAdapter = new Models.LibraryTableAdapters.BooksTableAdapter();
            Models.LibraryTableAdapters.MovesTableAdapter movesAdapter = new Models.LibraryTableAdapters.MovesTableAdapter();
            Models.Library.MovesDataTable movesTable = new Models.Library.MovesDataTable();

            long? delayFee = null;
            long? collectedBy = null;
            DateTime deadline = rentalsAdapter.DeadLine(member, bookId).Value;
            int latency = (DateTime.Today - deadline).Days;
            if(latency > 0)
            {
                delayFee = latency * 50;
                collectedBy = (long)Session["userId"];
            }
            rentalsAdapter.ReturnBook(DateTime.Today,delayFee,collectedBy, member, bookId);
            booksAdapter.IncreaseActiveStock(bookId);
            movesAdapter.AddMoves(member,bookId,DateTime.Today,false);
            ViewData["moves"] = movesTable.Rows;

            Response.Redirect("~/rentals/returnbook");
        }
    }
   
}

Views/Rentals/CurrentRentals.cshtml
@{ 
    System.Data.DataRowCollection rentals = (System.Data.DataRowCollection)ViewData["rentals"];
    string delay;
    int latency;
    
    foreach(Library.Models.Library.RentalsRow rentalRow in rentals)
    {
        delay = "";
        latency = (DateTime.Today - rentalRow.DeadLine).Days;
        if (latency >0)
        {
            delay = latency.ToString() + "gün ₺" + (latency * .50).ToString("F2");
        }
        <tr>
            <td>
               @rentalRow.Member.ToString()
            </td>
            <td>
                @rentalRow.MemberName @rentalRow.MemberSurname
            </td>
            <td>
                @rentalRow.RentedOn.ToString("dd-MM-yyyy")
            </td>
            <td>@rentalRow.DeadLine.ToString("dd-MM-yyyy")</td>
            <td style="color:red">@delay</td>
            <td>
                <input type="checkbox" name="member" onclick="changed(this)" value="@rentalRow.Member.ToString()"/>
            </td>
        </tr>
    }
}

Views/Rentals/Index.cshtml
@{ ViewBag.Title = "Index"; }

<h2>Ödünç Verme</h2>

<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script>
    function LoadBook() {
        var idBook = document.getElementById("bookId");
        $("#bookTable").load("@Url.Action("BookData","Books")/" + idBook.value);
    }
    function LoadMember() {
        var idMember = document.getElementById("memberId");
        $("#memberTable").load("@Url.Action("MemberData","Members")/" + idMember.value);
    }
</script>
<form action="~/rentals/processrental" method="post">
    <input type="number" name="bookId" id="bookId" placeholder="Kitap Id" data-val="true" data-val-required="Bu alan boş geçilemez!" data-val-range-min="1" />
    <span class="field-validation-valid" data-valmsg-for="bookId" data-valmsg-replace="true"></span>
    <input type="button" value="ARA" onclick="LoadBook()" />

    <table id="bookTable">
        <thead>
            <tr>
                <th>Kitap Id</th>
                <th>Kitap Adı</th>
                <th>Lokasyon</th>
                <th>Stok</th>
                <th>Kiralama Durumu</th>
            </tr>
        </thead>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>
                <input type="checkbox" disabled />
            </td>
        </tr>
    </table>

    <input type="number" name="memberId" id="memberId" placeholder="T.C. Kimlik No" data-val="true" data-val-required="Bu alan boş geçilemez!" data-val-range-min="10000000000"  data-val-range-max="99999999999"/>
    <span class="field-validation-valid" data-valmsg-for="memberId" data-valmsg-replace="true"></span>
    <input type="button" value="ARA" onclick="LoadMember()" />

    <table>
        <thead id="memberTable">
            <tr>
                <th>T.C. Kimlik No</th>
                <td>
                    <input type="number" name="memberId" placeholder="T.C. Kimlik No" data-val="true" data-val-required="Bu alan boş geçilemez!" data-val-range-min="10000000000"  data-val-range-max="99999999999" />
                    <span class="field-validation-valid" data-valmsg-for="memberId" data-valmsg-replace="true"></span>
                </td>
            </tr>
            <tr>
                <th>Adı</th>
                <td>
                    <input type="text" name="memberName" id="memberName" placeholder="Adı" data-val="true" data-val-required="Bu alan boş geçilemez!" maxlength="50" />
                    <span class="field-validation-valid" data-valmsg-for="memberName" data-valmsg-replace="true"></span>
                </td>
            </tr>
            <tr>
                <th>Soyadı</th>
                <td>
                    <input type="text" name="memberSurname" id="memberSurname" placeholder="Soyadı" data-val="true" data-val-required="Bu alan boş geçilemez!" maxlength="50" />
                    <span class="field-validation-valid" data-valmsg-for="memberSurname" data-valmsg-replace="true"></span>
                </td>
            </tr>
            <tr>
                <th>Telefon</th>
                <td>
                    <input type="number" name="memberPhone" id="memberPhone" placeholder="Telefon" data-val="true" data-val-required="Bu alan boş geçilemez!" data-val-range-min="1000000000"  data-val-range-max="9999999999" />
                    <span class="field-validation-valid" data-valmsg-for="memberPhone" data-valmsg-replace="true"></span>
                </td>
            </tr>
            <tr>
                <th>E-Posta</th>
                <td>
                    <input type="text" name="memberEMail" id="memberEMail" placeholder="E Posta" data-val="true" data-val-required="Bu alan boş geçilemez!" data-val-email="Geçersiz e-mail" maxlength="100" />
                    <span class="field-validation-valid" data-valmsg-for="memberEMail" data-valmsg-replace="true"></span>
                </td>
            </tr>
            <tr>
                <th>Cinsiyet</th>
                <td>
                    <label>Erkek</label>
                    <input type="radio" name="gender" value="true" />
                    <label>Kız</label>
                    <input type="radio" name="gender" value="false" />
                </td>
            </tr>
            <tr>
                <th>Yasaklı</th>
                <td>
                    <input type="checkbox" name="banned" disabled />
                </td>
            </tr>
            <tr>
                <th>Adres</th>
                <td>
                    <textarea name="memberAddress" id="memberAddress" placeholder="Adres" data-val="true" data-val-required="Bu alan boş geçilemez!" maxlength="200"></textarea>
                    <span class="field-validation-valid" data-valmsg-for="memberAddress" data-valmsg-replace="true"></span>
                </td>
            </tr>
        </thead>
        <thead>
            <tr>
                <th>Başlangıç:</th>
                <td>
                    @DateTime.Now.ToString("dd-MM-yyyy")
                </td>
            </tr>
            <tr>
                <th>Bitiş:</th>
                <td>
                    @DateTime.Now.AddDays(30).ToString("dd-MM-yyyy")
                </td>
            </tr>
        </thead>
    </table>
    <input type="submit" value="TAMAM" id="okButton" />
</form>
@if(ViewData["error"] != null)
{ 
    <p>@ViewData["error"]</p>
}

Views/Rentals/ReturnBook.cshtml
@{
    ViewBag.Title = "ReturnBook";
  
}

<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script>
    function LoadBook()
    {
        var idBook = document.getElementById("bookId");
         $("#bookTable").load("@Url.Action("BookData","Books")/" + idBook.value);
         $("#rentalsTable").load("@Url.Action("CurrentRentals","Rentals")/" + idBook.value);
    }
</script>
<script>
    function changed(termsCheckBox)
    {
        if (termsCheckBox.checked)
        {
            document.getElementById("button").disabled = false;
        }
        else
        {
            document.getElementById("button").disabled = true;
        }
    }
</script>
<form action="~/rentals/processreturn" method="post">
    <input type="number" name="bookId" id="bookId" data-val="true" data-val-required="Bu alan gerekli" />
    <span class="field-validation-valid" data-valmsg-for="bookId" data-valmsg-replace="true"></span>
    <input type="button" value="ARA" onclick="LoadBook()" />
    <table id="bookTable">
        <tr>
            <td>ADI:</td>
            <td></td>

        </tr>
        <tr>
            <td>Stok:</td>
            <td></td>
        </tr>
        <tr>
            <td>Lokasyon:</td>
            <td></td>
        </tr>
        <tr>
            <td>Ödünç:</td>
            <td>
                <input type="checkbox" disabled />
            </td>
        </tr>
    </table>
    <table>
        <thead>
            <tr>
                <th>TC Kimlik No</th>
                <th>Ad Soyad</th>
                <th>Kiralama Tarihi</th>
                <th>Geri Getirme Tarihi</th>
                <th>Gecikme</th>
                <th></th>
            </tr>
        </thead>
        <tbody id="rentalsTable"></tbody>
    </table>
    <input type="submit" id="button" disabled value="TAMAM" />
</form>